// export const LOGIN = "LOGIN";

// export const LOG_OUT = "LOG_OUT";

export const SAVE_USER_INFO = "SAVE_USER_INFO";

export const ON_LOGIN_PAGE = "ON_LOGIN_PAGE";

export const OFF_LOGIN_PAGE = "OFF_LOGIN_PAGE";

export const ON_SIGNUP_PAGE = "ON_SIGNUP_PAGE";

export const OFF_SIGNUP_PAGE = "OFF_SIGNUP_PAGE";

export const NEXT_STEP = "NEXT_STEP";

export const PREV_STEP = "PREV_STEP";

export const LOGIN_AUTHENTICATION_START = "AUTHENTICATION_START";

export const LOGIN_AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";

export const LOGIN_AUTHENTICATION_FAIL = "LOGIN_AUTHENTICATION_FAIL";

export const SIGNUP_AUTHENTICATION_START = "AUTHENTICATION_START";

export const SIGNUP_AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";

export const SIGNUP_AUTHENTICATION_FAIL = "SIGNUP_AUTHENTICATION_FAIL";

export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT";
